#!/bin/sh

echo " "

if [ "$BLOCK_BUTTON" = "1" ]; then
	kbdlang="$(echo "us\nbr\nru" | dmenu -p "Choose your keyboard language: " -fn "FiraCode Nerd Font:size=10" -nb "#101a20" -nf "#00ffc8" -sb "#00ffc8" -sf "#101a20")"
        if [ -z "$kbdlang" ]; then
		notify-send "   Keyboard language unchanged"
	else
		setxkbmap -layout "$kbdlang"
		notify-send "  Keyboard language set to: $kbdlang"
	fi
fi
