#!/bin/sh

mem="$(free -h | grep -E '^Mem:.*')"
total="$(echo $mem | cut -d " " -f 2)"
used="$(echo $mem | cut -d " " -f 3)"
echo " $used/$total"

if [ "$BLOCK_BUTTON" = "1" ]; then
	mem_bytes="$(free | grep -E '^Mem:.*')"
	total_bytes="$(echo $mem_bytes | cut -d " " -f 2)"
	used_bytes="$(echo $mem_bytes | cut -d " " -f 3)"
	notif="$(echo "Memory Usage : $(expr $used_bytes \* 100 / $total_bytes)%")"
	notify-send "$notif"
fi
